=== KatsiarynaArlouskaya/workspace/AT0007_Notepad_Maven/NotebookXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.com/Noutbook"
	xmlns:tns="http://www.epam.com/Noutbook">
	<element name="notes">
		<complexType>
			<sequence>
				<element name="note" type="tns:Note"
				minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="Note">
		<sequence>
			<element name="date" type="long"></element>
			<element name="content" type="string"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>
	
</schema>

=== KatsiarynaArlouskaya/workspace/AT0007_Notepad_Maven/Notebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:notes xmlns:tns="http://www.epam.com/Noutbook" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.epam.com/Noutbook NotebookXMLSchema.xsd ">
	<note id="0">
		<date>400000000000</date>
		<content>St Note one</content>
	</note>
	<note id="1">
		<date>401000000000</date>
		<content>St Note two</content>
	</note>
	<note id="2">
		<date>402000000000</date>
		<content>St Note three</content>
	</note>
	<note id="3">
		<date>403000000000</date>
		<content>St Note four</content>
	</note>


</tns:notes>

=== KatsiarynaArlouskaya/workspace/AT0007_Notepad_Maven/src/Notebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:notes xmlns:tns="http://www.epam.com/Noutbook" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.epam.com/Noutbook NotebookXMLSchema.xsd ">
	<note id="0">
		<date>100000</date>
		<content>Note one</content>
	</note>
	<note id="1">
		<date>200000</date>
		<content>Note two</content>
	</note>
	<note id="2">
		<date>300000</date>
		<content>Note three</content>
	</note>
	<note id="3">
		<date>400000</date>
		<content>Note four</content>
	</note>


</tns:notes>
